version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
      - "127.0.0.1:3001:5432"
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=dbJy32s2sk7
    volumes:
      - ./data:/var/lib/postgresql/data
